# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1500, 1000)
        MainWindow.setStyleSheet("background-image: url(:/new/images/background.jpg)\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = AnalogueGauageWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(550, 310, 411, 401))
        self.widget.setObjectName("widget")
        self.SpeedLCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.SpeedLCD.setGeometry(QtCore.QRect(680, 750, 161, 51))
        self.SpeedLCD.setStyleSheet("background: rgb(0, 0, 0);\n"
"color: white;\n"
"border-radius: 15px;")
        self.SpeedLCD.setObjectName("SpeedLCD")
        self.ACC_PB = QtWidgets.QPushButton(self.centralwidget)
        self.ACC_PB.setGeometry(QtCore.QRect(280, 360, 141, 71))
        font = QtGui.QFont()
        font.setFamily("Archivo")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ACC_PB.setFont(font)
        self.ACC_PB.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:0, x2:0.91, y2:0.58, stop:0.21393 rgba(52, 45, 141, 255), stop:0.99005 rgba(110, 255, 181, 255));\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(143, 38, 119, 255), stop:1 rgba(255, 65, 141, 255));\n"
"color: white;\n"
"font: 25pt \"Archivo\";\n"
"\n"
"")
        self.ACC_PB.setObjectName("ACC_PB")
        self.Mode_View = QtWidgets.QLineEdit(self.centralwidget)
        self.Mode_View.setGeometry(QtCore.QRect(660, 180, 181, 71))
        self.Mode_View.setStyleSheet("background: rgb(0, 0, 0);\n"
"font: 18pt \"Archivo\";\n"
"border-radius: 15px;")
        self.Mode_View.setText("")
        self.Mode_View.setObjectName("Mode_View")
        self.DefaultSpeed_BP = QtWidgets.QPushButton(self.centralwidget)
        self.DefaultSpeed_BP.setGeometry(QtCore.QRect(280, 460, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Archivo")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.DefaultSpeed_BP.setFont(font)
        self.DefaultSpeed_BP.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:0, x2:0.91, y2:0.58, stop:0.21393 rgba(52, 45, 141, 255), stop:0.99005 rgba(110, 255, 181, 255));\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(143, 38, 119, 255), stop:1 rgba(255, 65, 141, 255));\n"
"color: white;\n"
"font: 14pt \"Archivo\";\n"
"\n"
"")
        self.DefaultSpeed_BP.setObjectName("DefaultSpeed_BP")
        self.SetSpeed_SB = QtWidgets.QSpinBox(self.centralwidget)
        self.SetSpeed_SB.setGeometry(QtCore.QRect(280, 520, 141, 71))
        self.SetSpeed_SB.setMinimumSize(QtCore.QSize(141, 71))
        self.SetSpeed_SB.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(143, 38, 119, 255), stop:1 rgba(255, 65, 141, 255));\n"
"font: 30pt \"Archivo\";")
        self.SetSpeed_SB.setMinimum(60)
        self.SetSpeed_SB.setMaximum(100)
        self.SetSpeed_SB.setObjectName("SetSpeed_SB")
        self.LKS_PB = QtWidgets.QPushButton(self.centralwidget)
        self.LKS_PB.setGeometry(QtCore.QRect(1090, 580, 141, 71))
        font = QtGui.QFont()
        font.setFamily("Archivo")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.LKS_PB.setFont(font)
        self.LKS_PB.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:0, x2:0.91, y2:0.58, stop:0.21393 rgba(52, 45, 141, 255), stop:0.99005 rgba(110, 255, 181, 255));\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(143, 38, 119, 255), stop:1 rgba(255, 65, 141, 255));\n"
"color: white;\n"
"font: 25pt \"Archivo\";\n"
"\n"
"")
        self.LKS_PB.setObjectName("LKS_PB")
        self.LDW_PB = QtWidgets.QPushButton(self.centralwidget)
        self.LDW_PB.setGeometry(QtCore.QRect(1090, 470, 141, 71))
        font = QtGui.QFont()
        font.setFamily("Archivo")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.LDW_PB.setFont(font)
        self.LDW_PB.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:0, x2:0.91, y2:0.58, stop:0.21393 rgba(52, 45, 141, 255), stop:0.99005 rgba(110, 255, 181, 255));\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(143, 38, 119, 255), stop:1 rgba(255, 65, 141, 255));\n"
"color: white;\n"
"font: 25pt \"Archivo\";\n"
"\n"
"")
        self.LDW_PB.setObjectName("LDW_PB")
        self.AEB_PB = QtWidgets.QPushButton(self.centralwidget)
        self.AEB_PB.setGeometry(QtCore.QRect(1090, 360, 141, 71))
        font = QtGui.QFont()
        font.setFamily("Archivo")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.AEB_PB.setFont(font)
        self.AEB_PB.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:0, x2:0.91, y2:0.58, stop:0.21393 rgba(52, 45, 141, 255), stop:0.99005 rgba(110, 255, 181, 255));\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(143, 38, 119, 255), stop:1 rgba(255, 65, 141, 255));\n"
"color: white;\n"
"font: 25pt \"Archivo\";\n"
"\n"
"")
        self.AEB_PB.setObjectName("AEB_PB")
        self.Speed_PB = QtWidgets.QPushButton(self.centralwidget)
        self.Speed_PB.setGeometry(QtCore.QRect(280, 620, 141, 31))
        self.Speed_PB.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:0, x2:0.91, y2:0.58, stop:0.21393 rgba(52, 45, 141, 255), stop:0.99005 rgba(110, 255, 181, 255));\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(143, 38, 119, 255), stop:1 rgba(255, 65, 141, 255));\n"
"color: white;\n"
"font: 14pt \"Archivo\";\n"
"\n"
"")
        self.Speed_PB.setObjectName("Speed_PB")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ACC_PB.setText(_translate("MainWindow", "ACC"))
        self.Mode_View.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.DefaultSpeed_BP.setText(_translate("MainWindow", "Default ON"))
        self.LKS_PB.setText(_translate("MainWindow", "LKS"))
        self.LDW_PB.setText(_translate("MainWindow", "LDW"))
        self.AEB_PB.setText(_translate("MainWindow", "AEB"))
        self.Speed_PB.setText(_translate("MainWindow", "Set Speed"))
from AnalogueGauageWidget import AnalogueGauageWidget
import image_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
